-- This package contains the definition of partial gnerators used for multiplications/division purposes. It contains: 
-- * Definition of Baugh-Wooley generator 

-- To use this components, include le library in your compiler (for example Vivado) and add the following line: 
-- use work.GENERATORS.ALL 

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

package GENERATORS is
    -- Partials type used from the generators to contain the outputs. It is a matrix of STD_LOGIC (the rows correspond to different partials)
    type PARTIALS is array (natural range <>, natural range <>) of STD_LOGIC; 

    -- Definition of parametric Baugh-Wooley generator and respective functions 
    component bw_generator is
        Generic ( 
            DATA_SIZE: INTEGER := 8
        );
        Port (
            data_a: in STD_LOGIC_VECTOR(DATA_SIZE-1 downto 0);
            data_b: in STD_LOGIC_VECTOR(DATA_SIZE-1 downto 0);
    
            partials_out: out PARTIALS(DATA_SIZE-1 downto 0,DATA_SIZE downto 0)
        );
    end component;
    
    -- The following functions are used to obtain the size of the output partial matrix in compile time (for generation of matrices with parametric sizes)

    -- get_bw_partial_size Returns the size of the partials generated by the BW-generator (for example for 8 bit inputs, it generates partials of 9 bits)
    function get_bw_partial_size (
        DATA_SIZE:  INTEGER 
    ) return        INTEGER;

    -- get_bw_partials_to_reduce Returns the number of partials to reduce (for example, for 8 bit inputs, it generates 8 partials) 
    function get_bw_partials_to_reduce (
        DATA_SIZE:  INTEGER 
    ) return        INTEGER;
    
    -- get_bw_partial_shift Returns the shift that should be applied to the partials for obtaining the result of the multiplication (fixed to 1)
    function get_bw_partial_shift
      return        INTEGER;
 
   ------------------------------------------------------- 
end package; 

package body GENERATORS is 
    function get_bw_partial_size (
        DATA_SIZE:      INTEGER)
        return          INTEGER is 
    begin 
        return DATA_SIZE+1;
    end function;
    
    function get_bw_partials_to_reduce (
        DATA_SIZE:      INTEGER) 
        return          INTEGER is 
    begin 
        return DATA_SIZE; 
    end function; 
    
    function get_bw_partial_shift 
        return        INTEGER is 
    begin 
        return 1;
    end function; 
end package body; 
