library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

package MATRIX_REDUCTION_PARAMETERS is
    -- Definition of the partials format 
    constant MATRIX_PARTIAL_SIZE:       integer := 9;
    constant MATRIX_PARTIALS_TO_REDUCE: integer := 8;
    constant MATRIX_PARTIAL_SHIFT:      integer := 1;
    constant MATRIX_OUTPUT_SIZE:        integer := MATRIX_PARTIAL_SIZE+(MATRIX_PARTIALS_TO_REDUCE-1); 
    
    -- Definition of partials array (partial is an array of STD_LOGIC and the entire metrix is an 2-dim array of STD_LOGIC)
    
    type MATRIX_ROW is array (0 to MATRIX_OUTPUT_SIZE-1) of STD_LOGIC;
    type MATRIX is array (natural range <>) of MATRIX_ROW; 
    
    -- function used to estimate the current height of the input partials tree knowing the column index i. 
    -- Example 1: PARTIALS_SIZE=9, PARTIALS_IN=4 and PARTIALS_TO_REDUCE = 8 
    -- 16 * * * * * * * * * * * * * * * 0
    --    * * * * * * * * * * * * * * *
    --      * * * * * * * * * * * * *
    --      * * * * * * * * * * * *
    --                  
    -- get_tree_column_height(6,4) = 4 
    -- The estimation consider also the carry generated when the input partials are processed by a precedent stage. 

    
    function get_matrix_column_height( 
        c:                  INTEGER;        -- column selected 
        matrix_rows_in:     INTEGER         -- Number of input partials 
        
    ) return                INTEGER;
    
    -- Function to estimate the carry generated by a reduction from partials_in to partials_out. 
    -- Example: partials in = 4 partials_out=3, RADIX-4 
    -- 16 * * * * * * * * * * * * * * * 0
    --      * * * * * * * * * * * * * 
    --          * * * * * * * * *               <- partials out = 3 
    --              * * * * *                   <- partials in = 3
    --          R R R R R R R 
    --        C C C C C C C                     <- carrys generated from previous column
    --        
    --   
    function get_matrix_column_carrys(
        c:                  INTEGER;
        matrix_rows_in:     INTEGER;
        matrix_rows_out:    INTEGER
    ) return                INTEGER; 
    
    function get_matrix_column_half_adders(
        c:                  INTEGER;
        matrix_rows_in:     INTEGER;
        matrix_rows_out:    INTEGER  
    ) return                INTEGER;
    
    function get_matrix_column_full_adders(
        c:                  INTEGER;
        matrix_rows_in:     INTEGER;
        matrix_rows_out:    INTEGER 
    ) return                INTEGER;
    
end package;

package body MATRIX_REDUCTION_PARAMETERS is
    function get_matrix_column_height( 
        c:              INTEGER;
        matrix_rows_in: INTEGER) 
        return          INTEGER is 
        
        variable ASCENDING_HEIGHT:  INTEGER; 
        variable DESCENDING_HEIGHT: INTEGER;     
        variable LAST_CARRY_POS:    INTEGER;
        variable CONSTANT_HEIGHT:   INTEGER;
    
    begin 
        -- Same encoding used in  get_tree_column_height
        ASCENDING_HEIGHT := (c+MATRIX_PARTIAL_SHIFT)/MATRIX_PARTIAL_SHIFT;
        DESCENDING_HEIGHT := (MATRIX_OUTPUT_SIZE + MATRIX_PARTIAL_SHIFT -c -1)/MATRIX_PARTIAL_SHIFT;
        CONSTANT_HEIGHT := matrix_rows_in;
        LAST_CARRY_POS:= (MATRIX_PARTIAL_SHIFT*(MATRIX_PARTIALS_TO_REDUCE-matrix_rows_in))+(MATRIX_PARTIAL_SIZE);

        -- Example: partials in = 4 PARTIALS_TO_REDUCE=5, RADIX-4 
        -- | des  |   const         | asc   |
        -- 16 * * * * * * * * * * * * * * * 0
        --        * * * * * * * * * * *  
        --            * * * * * * *                <- partials out = 3 
        --              * * * *                    <- partials in = 3
        --              ^
        --        LAST_CARRY_POS
        
        if (c<0 or c>(MATRIX_OUTPUT_SIZE-1)) then
            return 0; 
        end if; 
        
        if (ASCENDING_HEIGHT < matrix_rows_in) then 
            return ASCENDING_HEIGHT;
        elsif ((DESCENDING_HEIGHT < matrix_rows_in) and ((c>LAST_CARRY_POS) or (matrix_rows_in=MATRIX_PARTIALS_TO_REDUCE))) then 
            return DESCENDING_HEIGHT;
        else
            return CONSTANT_HEIGHT;
        end if;
            
    end function;
    
    
    function get_matrix_column_carrys( 
        c:                  INTEGER;
        matrix_rows_in:     INTEGER;
        matrix_rows_out:    INTEGER 
    ) return                INTEGER is 

        variable ASCENDING_HEIGHT:  INTEGER; 
        variable DESCENDING_HEIGHT: INTEGER;     
        variable LAST_CARRY_POS:    INTEGER;
        variable CONSTANT_HEIGHT:   INTEGER;
    begin      
        -- Example: partials in = 4 partials_out=3, RADIX-4 
        -- | des  |   const         | asc   |
        -- 16 * * * * * * * * * * * * * * * 0
        --        * * * * * * * * * * *  
        --            * * * * * * *                 <- partials out = 3 
        --              * * * * *                   <- partials in = 4
        --              R R R R R 
        --            C C C C C                     <- carrys generated from previous column
        --            ^
        --    LAST_CARRY_POS (next stage)
        
        ASCENDING_HEIGHT := (c+MATRIX_PARTIAL_SHIFT)/MATRIX_PARTIAL_SHIFT;
        DESCENDING_HEIGHT := (MATRIX_OUTPUT_SIZE + MATRIX_PARTIAL_SHIFT -c -1)/MATRIX_PARTIAL_SHIFT;
        LAST_CARRY_POS:= (MATRIX_PARTIAL_SHIFT*(MATRIX_PARTIALS_TO_REDUCE-matrix_rows_in))+(MATRIX_PARTIAL_SIZE);
        CONSTANT_HEIGHT:=matrix_rows_in;
        
        if (c<0 or c>(MATRIX_OUTPUT_SIZE-1)) then
            return 0; 
        end if; 
        
        if (ASCENDING_HEIGHT <= matrix_rows_out or DESCENDING_HEIGHT < matrix_rows_out) then 
            return 0;
        else
            if (ASCENDING_HEIGHT < matrix_rows_in) then 
                return ASCENDING_HEIGHT-matrix_rows_out; 
            elsif ((DESCENDING_HEIGHT < matrix_rows_in) and ((c>LAST_CARRY_POS))) then 
                return DESCENDING_HEIGHT+1-matrix_rows_out;
            else
                return CONSTANT_HEIGHT-matrix_rows_out;
            end if;
        end if;
                
    end function;
    
    function get_matrix_column_half_adders( 
        c:                  INTEGER;
        matrix_rows_in:     INTEGER;
        matrix_rows_out:    INTEGER 
    ) return                INTEGER is 

        variable PREVIOUS_CARRYS: INTEGER;
        variable HEIGHT:          INTEGER; 
       
    begin      
        PREVIOUS_CARRYS := get_matrix_column_carrys(c-1,matrix_rows_in,matrix_rows_out);
        HEIGHT := get_matrix_column_height(c,matrix_rows_in);
        
        if (PREVIOUS_CARRYS+HEIGHT<matrix_rows_out) then 
            return 0; 
        else 
            return (PREVIOUS_CARRYS-matrix_rows_out+HEIGHT) mod 2;
        end if;
        
    end function;
    
    function get_matrix_column_full_adders( 
        c:                  INTEGER;
        matrix_rows_in:     INTEGER;
        matrix_rows_out:    INTEGER  
    ) return                INTEGER is 
    
        variable PREVIOUS_CARRYS: INTEGER;
        variable HEIGHT:          INTEGER; 
       
    begin      
        PREVIOUS_CARRYS := get_matrix_column_carrys(c-1,matrix_rows_in,matrix_rows_out);
        HEIGHT := get_matrix_column_height(c,matrix_rows_in);
        if (PREVIOUS_CARRYS+HEIGHT<matrix_rows_out) then 
            return 0;
        else 
            return (PREVIOUS_CARRYS-matrix_rows_out+HEIGHT)/2;
        end if;
    end function;

end package body;

