library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

package MULTIPLIER_PARAMETERS is
    -- Definition of the partials format 
    
    -- The multiplicator uses a booth radix algorithm to decompose the first multiplication into more partials to add using a dadda tree 
    -- To edit the radix format and the data size change these two variables: 
    constant DATA_SIZE:             integer := 8;   -- Dimension of the input numbers to multiply in bits 
    constant RADIX_WINDOW_SIZE:     integer := 3;   -- Type of the radix algorithm (2 for Radix-2, 3 for Radix-4, 4 for Radix-8) 
    
    -- Partial size and number of partials to reduce are automatically calculated using DATA_SIZE and RADIX_WINDOW_SIZE
    constant RADIX_WINDOW_SHIFT:    integer := RADIX_WINDOW_SIZE-1;     -- number of bits to shilft to process the next partial
    constant RADIX_MAX_SHIFT:       integer := RADIX_WINDOW_SIZE-2;     -- maximum shift of the multiplier introduced in the radix partial generator
    constant PARTIAL_SIZE:          integer := (DATA_SIZE*2)+1; 
    constant PARTIALS_TO_REDUCE:    integer := ((DATA_SIZE + RADIX_MAX_SHIFT) + RADIX_WINDOW_SHIFT -1)/RADIX_WINDOW_SHIFT; 
    
    -- Definition of partials array (partial is an array of STD_LOGIC and the entire metrix is an 2-dim array of STD_LOGIC)
    
    type PARTIAL is array (0 to PARTIAL_SIZE-1) of STD_LOGIC;
    type PARTIALS_ARRAY is array (natural range <>) of PARTIAL; 
    
    -- function used to estimate the current height of the input partials tree knowing the column index i. 
    -- Example 1: radix-4 with partials in = 5 and PARTIALS_TO_REDUCE = 5, RADIX-4 
    -- 16 * * * * * * * * * * * * * * * 0
    --      * * * * * * * * * * * * * 
    --          * * * * * * * * * 
    --              * * * * *
    --                  * 
    -- get_tree_column_height(6,5,4) = 4 
    -- The estimation consider also the carry generated when the input partials are processed by a precedent stage. 
    -- Example 1: radix-4 with partials in = 3 and PARTIALS_TO_REDUCE = 5, RADIX-4 
    -- 16 * * * * * * * * * * * * * * * 0
    --      * * * * * * * * * * * * * 
    --        * * * * * * * * * * 
    -- get_tree_column_height(13,5,4) = 3 
    
    function get_tree_column_height( 
        i:              integer;        -- column selected 
        partials_in:    integer         -- Number of input partials 
        
    ) return        integer;
    
    -- Function to estimate the carry generated by a reduction from partials_in to partials_out. 
    -- Example: partials in = 4 partials_out=3, RADIX-4 
    -- 16 * * * * * * * * * * * * * * * 0
    --      * * * * * * * * * * * * * 
    --          * * * * * * * * *               <- partials out = 3 
    --              * * * * *                   <- partials in = 3
    --          R R R R R R R 
    --        C C C C C C C                     <- carrys generated from previous column
    --        
    --   
    function get_tree_column_carrys(
        i:              integer;
        partials_in:    integer;
        partials_out:   integer 
    ) return        integer; 
    
    function get_tree_column_half_adders(
        i:              integer;
        partials_in:    integer;
        partials_out:   integer 
    ) return        integer;
    
    function get_tree_column_full_adders(
        i:              integer;
        partials_in:    integer;
        partials_out:   integer 
    ) return        integer;
    
end package;

package body MULTIPLIER_PARAMETERS is
    function get_tree_column_height( 
        i: integer;
        partials_in: integer) 
        return integer is 
        
        variable ASCENDING_HEIGHT: integer; 
        variable DESCENDING_HEIGHT: integer; 
        variable CONSTANT_HEIGHT: integer;     
        variable HEIGHT: integer;    
        variable LAST_CARRY_POS: integer;
    
    begin 
        -- Same encoding used in  get_tree_column_height
        ASCENDING_HEIGHT := (i+RADIX_WINDOW_SHIFT)/RADIX_WINDOW_SHIFT;
        DESCENDING_HEIGHT := (PARTIAL_SIZE + RADIX_WINDOW_SHIFT -i -1)/RADIX_WINDOW_SHIFT;
        CONSTANT_HEIGHT := PARTIALS_IN;
        LAST_CARRY_POS:= (RADIX_WINDOW_SHIFT*(PARTIALS_TO_REDUCE-partials_in))+(DATA_SIZE+RADIX_MAX_SHIFT);

        -- Example: partials in = 4 PARTIALS_TO_REDUCE=5, RADIX-4 
        -- | des  |   const         | asc   |
        -- 16 * * * * * * * * * * * * * * * 0
        --        * * * * * * * * * * *  
        --            * * * * * * *                <- partials out = 3 
        --              * * * *                    <- partials in = 3
        --              ^
        --        LAST_CARRY_POS
        
        if (i<0) then
            return 0; 
        end if; 
        
        if (ASCENDING_HEIGHT < partials_in) then 
            HEIGHT:= ASCENDING_HEIGHT;
        elsif ((DESCENDING_HEIGHT < partials_in) and ((i>LAST_CARRY_POS) or (partials_in=PARTIALS_TO_REDUCE))) then 
            HEIGHT:= DESCENDING_HEIGHT;
        else
            HEIGHT:= CONSTANT_HEIGHT;
        end if;
            
        return HEIGHT;
    end function;
    
    
    function get_tree_column_carrys( 
        i:              integer;
        partials_in:    integer;
        partials_out:   integer 
    ) return        integer is 

        variable CARRYS: integer;
        variable ASCENDING_HEIGHT: integer; 
        variable DESCENDING_HEIGHT: integer; 
        variable CONSTANT_HEIGHT: integer;     
        variable LAST_CARRY_POS: integer;
       
    begin      
        -- Example: partials in = 4 partials_out=3, RADIX-4 
        -- | des  |   const         | asc   |
        -- 16 * * * * * * * * * * * * * * * 0
        --        * * * * * * * * * * *  
        --            * * * * * * *                 <- partials out = 3 
        --              * * * * *                   <- partials in = 4
        --              R R R R R 
        --            C C C C C                     <- carrys generated from previous column
        --            ^
        --    LAST_CARRY_POS (next stage)
        
        ASCENDING_HEIGHT := (i+RADIX_WINDOW_SHIFT)/RADIX_WINDOW_SHIFT;
        DESCENDING_HEIGHT := (PARTIAL_SIZE + RADIX_WINDOW_SHIFT -i -1)/RADIX_WINDOW_SHIFT;
        CONSTANT_HEIGHT := PARTIALS_IN;     
        LAST_CARRY_POS:= (RADIX_WINDOW_SHIFT*(PARTIALS_TO_REDUCE-partials_out))+(DATA_SIZE+RADIX_MAX_SHIFT);
        
        if (i<0) then
            return 0; 
        end if; 
        
        if (ASCENDING_HEIGHT <= partials_out) then 
            CARRYS:= 0;
        elsif (DESCENDING_HEIGHT < partials_out and i>LAST_CARRY_POS) then 
            CARRYS:= 0;
        else
            CARRYS:= PARTIALS_IN-PARTIALS_OUT;
        end if;
                
        return CARRYS;
    end function;
    
    function get_tree_column_half_adders( 
        i:              integer;
        partials_in:    integer;
        partials_out:   integer 
    ) return        integer is 

        variable PREVIOUS_CARRYS: integer;
        variable HEIGHT: integer; 
        variable HALF_ADDERS: integer; 
       
    begin      
        PREVIOUS_CARRYS := get_tree_column_carrys(i-1,partials_in,partials_out);
        HEIGHT := get_tree_column_height(i,partials_in);
        
        if (PREVIOUS_CARRYS+HEIGHT<partials_out) then 
            HALF_ADDERS := 0; 
        else 
            HALF_ADDERS := (PREVIOUS_CARRYS-partials_out+HEIGHT) mod 2;
        end if;
        return HALF_ADDERS;
        
    end function;
    
    function get_tree_column_full_adders( 
        i:              integer;
        partials_in:    integer;
        partials_out:   integer 
    ) return        integer is 
    
        variable PREVIOUS_CARRYS: integer;
        variable HEIGHT: integer; 
        variable FULL_ADDERS: integer; 
       
    begin      
        PREVIOUS_CARRYS := get_tree_column_carrys(i-1,partials_in,partials_out);
        HEIGHT := get_tree_column_height(i,partials_in);
        if (PREVIOUS_CARRYS+HEIGHT<partials_out) then 
            FULL_ADDERS := 0;
        else 
            FULL_ADDERS := (PREVIOUS_CARRYS-partials_out+HEIGHT)/2;
        end if;
        return FULL_ADDERS;
    end function;
    
    

end package body;

